### Logs In
# @name login
GET http://localhost:4000/token/login?username=exampleUser&password=strongPassword123
Content-Type: application/json

### Logout User
GET http://localhost:4000/token/logout
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

### renew a token
POST http://localhost:4000/token/renew
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token={{login.response.body.refreshToken}}

### Check if a token is valid, or not
GET http://localhost:4000/token/verify
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json
