### Register a new user
GET http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZXhhbXBsZVVzZXIiLCJpYXQiOjE3NTEzODMwNDAsImV4cCI6MTc1MTM4MzEwMH0.ODG4-Ns82_hM5HzCVftWMB-p4WfEy3Ti4PKx7qlk2Y2pMU4ugeYPcBHJwqn8l9gvyWyyrivBDf3G_PfE-KWSQBNeP_ahwiLTJATCQUxT_kmz9eVSTWddoSBbcbjg5cytN_SH4xL56bt9y_fwqYaghq6Grr8cAtPZtdUnNFaVR9A8DMvAZrCWcqKoGQOAHgInVQkcU6cN_CRy7t_pWclzs4TnqiqrHeNDstu17Kx4nhjnHDUESaOOznm7lnixkOCyUEcoBqbev7Ru8ecNgCxU9iyMjqO-e2Tql7ImSwYY1pfq1L9FuzRTgv9y8c9LTa-Fbh3F4rKA90nq3bAjVofctj7KVdoOHIL_9BHD1NrtK2kXRkgtZukj-peCUc2ybjFF7vYdpHp9ZZyfbEkZZGNvG_D_OOgorjFSAY2aFWjak0oNLRl2UxT5_rwcbT4OOLt0_yqd_qOFj4-8dWhmL7FUVmTI9sXHoZZC9VDiOIT8WahktN1M0H1_g4GPdcWbcUYq3h2Mu97iP-cvbIKbw_SBU63sBcI8_UBpS7rJ84r2VmeqT2UG-sFK5peYBixAdR61YxtEERfki1lhf7VCVTUNaTII5ht6IRzSDZXf8kv5CFVxeAuVDFeGe_KjtZmFgvzuCoRiUo2zmNaG0ExK86s-_7z0U8ftVWhxFFbFIQvInZU
Content-Type: application/json
