services:
  eas-code:
    build: .
    container_name: eas-app
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    depends_on:
      - eas-mongo
    env_file:
      - .env
    develop:
      watch:
        - path: ./src/
          action: rebuild
          ignore:
            - "**/node_modules/**"
            - "**/*.!(ts)"  # ignore non-TypeScript files
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./.env
          action: rebuild
    
  eas-mongo:
    image: mongo:8
    container_name: eas-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - 27017:27017
    volumes:
      - mongo-data-db:/data/db
      - mongo-data-configdb:/data/configdb
    restart: unless-stopped

volumes:
  mongo-data-db:
  mongo-data-configdb:
