### Register a new user
GET http://localhost:4000/verify
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZXhhbXBsZVVzZXIiLCJpYXQiOjE3NTEyOTU3OTMsImV4cCI6MTc1MTI5NTg1M30.OvKi4nJuTd3KPnDz0twmp3Nj-0SlGGHI-aTapI2_4KILLEg4nNelmDGnIZEaIM7CxUpIXAe1BWF2I6Q1-H_1r-cHocOxdllIaNMBogBnXDaSj4ECRvWwBQFntlmAGOISGT1XfomRCeWUc1tu0X_fp5JFline7Oq8JF11mA5JLhQU4CGQ64AFC4EMUt3ot4O1OJMYxpRl6ZDaURa_RW5b2XFC2BzqKE7glQoQNpcHbPKpH0xHyfew6dZArF3jzbNSgGRGHVnH9Dmex6mBgszba1P9iyyiSzlUAfImwtgYs5Cf5vznf9zXLJqGwmYuECRx-WTtiMUJSfAqdcM1hCtwMvr13J_lJyiZ-VOIVdHb34e6Yf5JYD2KJRGb-OJY2LywPJgJ9Gtu_q4Vyyj-MMM8ES5OEYyP_AKWIP_TVzqZtkNcVYVPuCyzh2kUi29RTQ_xeAOQoY1AEbW5CrPazezQ5jlV2aEMjbIXNJiONGtgOmzPd7Xb6HModvoICPmRpv0unUBxkf4sxgBeH8dDIGR5DAIn4V8Ya0oxqpxE7L6JBtiQzANgrPLYbiwQQF553KRFr72lZaesz2eOxzrXsslgqRX0faGGNooZW_RcJRgJcb_DmZa-FfAGWtmA4OpNnS_gdHduuextCkuH9AMXwWIa4INQdDBE4Fqk9mfOwo7nEIA
Content-Type: application/json