### Register a new user
GET http://localhost:4000/verify
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZXhhbXBsZVVzZXIiLCJpYXQiOjE3NTEyOTM5MzgsImV4cCI6MTc1MTI5Mzk5OH0.qrS5o3VoEujNe_ZqtV4nbhkMCz-X-mGVzK4p19xFVO5u_B94UVxyLUNPHJWu-_7_RwSf4sSGTTcG0Pv6d8xBEUPKuJLXJFs7stgzIZ-7GIiSfsds0a5zYLfmtsa1Fw0MxkOoR_KNL75kN1IvXlb2ypMezNYxlEHqHCFRnQRO69Uj1IFvTTTWKZwG1zMHB312C3istKYH_w90GwCJ2P2Iv7J5upzIfq4FWxrJv8CMcK9Gql6qzyW0TJN9-_3-7DhFCo_mR7367ACFXkRmecYU3GA8tOcKGEZfEoxC9iSOtDduG-jOSv8mzGVf0djBEDfKtmF6L4u4fzzGRR6B3_zWCAU0x3C8_O6Oh7_5pw0AtZk182vfBRwlf2ex0ZEkfK7AZuWcVj-9xQYuxX-8s-NHTjL0VnKrUO5B4PYuj9_kyAg6WrwYIOoHiH7hXbuGvl3dWIhXji6al3KO-3HNU3IBqTX1s0CAWYBoMv8YnZjaJ72_9jXR4CJrVMB2R7z8hqgVJMe_C8gkHB2J19uYHM8FQU4e1h6rA1T2cY941IKbyzraNrX6k-iznjzlV2DugOyyJhIeBJDq9jtjSCcgIGrqVft2_b1Mh6CiIQM_5dKGMSywmydCUdS1bR3qhQa7jdtThAVE6m6SR9VUOds8UIpQT9_n-QjNlDg8UFyL2he2AjM
Content-Type: application/json