### Register a new user
GET http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZXhhbXBsZVVzZXIiLCJpYXQiOjE3NTEyOTcyMjMsImV4cCI6MTc1MTI5NzI4M30.Yw7FdqCCKa_Md3UMcqkox8e5Dr5bGnK5yLEa643L1Sxm7LCdGMxU8pR9HPI3H8gfCteH3bb5plEXAUVyz4vYbFuuaChkcipJraxaQKxyhlRLqKRV0oibmwy8Al2krIhGj9z1ouAbZE0_VX08Hy0PivfyiVEIvVShmWuN4iSaTyqzFQRFL4JSOwjFd9z5ZRLlUeTUoJlx2yr3bwhKN_8w4y-gCd0GondHWTuoXw6FldnOGrO7l4zwRSF2RKHggc40a3kdp2-MiLcEzEmm3bJ_2AccNrYLJqyU4KL_qJ5l_4nm451Z0WPGhHN6aWB-LtrpBeiEU7C5qV8xg2huFU0sn_wt3utJKq6R6SaRKWv2nA8cQmo8EKCm_gz0xKZ7jAAPcB5r8D9MXZNaOAqXWNvhBJQkZ9_Jh_lZwYESSIXOTz62FmDWwtYdbSrungnnnxEP6_4bV_bDkJ5vRD9RsIwMNBSUwr8rMynnqj_bcxIlk11IsMd_oU4sLjZo940sM4yylV4EhRZn_a8OON-UIYmPF2I5oLjV10YPEKjOTkWdYtV0rslDRpJMW9S__UQPh0yM8RE-IVB58Zeqf82rnQdxIlGYPMENGPVd5AqZXrCz3vT9VHhC40dS2GTWcROUkQSL3VB1uUC_zXLPO5kmCXKGk3pi9FDjRPKMSXMMkpQikyo
Content-Type: application/json
